#pragma once

#define SUPER_SCANNER_DEVICE 0x8080
#define IOCTL_MAJOREXAMPLE_HELLOWORLD CTL_CODE(SUPER_SCANNER_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SUPER_SCANNER_MAX_PATH 260

#define DRIVER_TAG 'YEP'
#define DRIVER_NAME L"MajorExample"





